# Generated by Django 3.2.25 on 2025-06-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormBaseline',
            fields=[
                ('file_type', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('base_font_names', models.JSONField(default=list)),
                ('base_font_size', models.JSONField(default=list)),
                ('font_size_tolerance', models.IntegerField(default=0)),
            ],
        ),
    ]
